#pragma once
#define NV_TENSORRT_MAJOR 1
#define NV_TENSORRT_MINOR 1
#define NV_TENSORRT_PATCH 0
#define NV_TENSORRT_BUILD 0

#define NV_TENSORRT_SONAME_MAJOR 1
#define NV_TENSORRT_SONAME_MINOR 1
#define NV_TENSORRT_SONAME_PATCH 0
